title: Dossier thématique Winckelmann
logo:
description: réalisé par l'Institut national d'histoire de l'art
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author: Institut national d'histoire de l'art
github:
  is_project_page: false
