title: Dossier thématique Winckelmann
logo:
description: Vous trouverez ici la version numérique des cartels de l'exposition dossier réalisée par l'Institut national d'histoire de l'art
show_downloads: false
markdown: kramdown
google_analytics:
theme: jekyll-theme-minimal
author: Institut national d'histoire de l'art
github:
  is_project_page: false
