title: Dossier thématique Winckelmann
logo:
description: Exposition dossier du 22 au 30 novembre 2018 à la bibliothèque de l'Institut national d'histoire de l'art
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author: Institut national d'histoire de l'art
github:
  is_project_page: false
