title: Exposition Winckelmann
logo: ./img/winckelmann.jpeg
description:
  En accompagnement du colloque [Winckelmann et l’œuvre d’art:Matériaux et types](http://bit.ly/2P8x3Ar), la bibliothèque de l’INHA présentera en salle Labrouste une exposition dossier autour de ce « père fondateur » de l’histoire de l’art et de l’archéologie. Cette expérimentation de publication en ligne permttra de retrouver la description des objets représentés. [editor on GitHub](https://github.com/antoinecourtin/text_expoVirtuelle/edit/master/index.md)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author: Institut national d'histoire de l'art
twitter_username: jekyllrb
github:
  is_project_page: false
