title: Minimal theme
logo: /https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Johann_Joachim_Winckelmann_%28Angelika_Kaufmann%29.jpg/220px-Johann_Joachim_Winckelmann_%28Angelika_Kaufmann%29.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
