title: Dossier thématique
logo: ./img/winckelmann.jpeg
description:
  En accompagnement du colloque, la bibliothèque de l’INHA présentera en salle Labrouste une exposition dossier autour de ce « père fondateur » de l’histoire de l’art et de l’archéologie. Cette expérimentation de publication en ligne permttra de retrouver la description des objets représentés.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author: Institut national d'histoire de l'art
github:
  is_project_page: false
